<a href="https://colab.research.google.com/github/spacee48/SIT719/blob/main/5_2_dataset2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Random Forest(RF) on IoT Combined Dataset**

Importing libraries

In [2]:
import timeit
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')
#warnings.filterwarnings('always')

**Upload File**

In [3]:
#uploaded = files.upload()

**Importing the Dataset**

In [7]:
import io
import pandas as pd
from google.colab import files

uploaded = files.upload()
filename = list(uploaded.keys())[0]

dataset = pd.read_csv(io.BytesIO(uploaded[filename]))

Saving Processed_Combined_IoT_dataset.csv to Processed_Combined_IoT_dataset (4).csv


**Exploratory Data Analysis**

In [8]:
dataset.head()

FC1_Read_Input_Register  FC2_Read_Discrete_Value  \
0                 0.495216                 0.499092   
1                 0.495216                 0.499092   
2                 0.495216                 0.499092   
3                 0.495216                 0.499092   
4                 0.495216                 0.499092   

   FC3_Read_Holding_Register  FC4_Read_Coil  current_temperature  door_state  \
0                   0.488897       0.499405             0.344399           0   
1                   0.488897       0.499405             0.344399           0   
2                   0.488897       0.499405             0.344399           0   
3                   0.488897       0.499405             0.344399           0   
4                   0.488897       0.499405             0.344399           0   

   fridge_temperature  humidity  latitude  light_status  longitude  \
0            0.930769  0.462511  0.008217             0   0.008112   
1            0.588462  0.462511  0.008217             0   0.008112   
2            0.076923  0.462511  0.008217             0   0.008112   
3            0.292308  0.462511  0.008217             0   0.008112   
4            0.746154  0.462511  0.008217             0   0.008112   

   motion_status  pressure  sphone_signal  temp_condition  temperature  \
0              0  0.533556       0.666667             0.2     0.517307   
1              0  0.533556       0.666667             0.2     0.517307   
2              0  0.533556       0.666667             0.8     0.517307   
3              0  0.533556       0.666667             0.8     0.517307   
4              0  0.533556       0.666667             0.2     0.517307   

   thermostat_status  label  
0                  1      0  
1                  1      0  
2                  1      0  
3                  1      0  
4                  1      0

In [9]:
print(dataset.shape)

(401119, 18)


In [10]:
print(list(dataset.columns))

['FC1_Read_Input_Register', 'FC2_Read_Discrete_Value', 'FC3_Read_Holding_Register', 'FC4_Read_Coil', 'current_temperature', 'door_state', 'fridge_temperature', 'humidity', 'latitude', 'light_status', 'longitude', 'motion_status', 'pressure', 'sphone_signal', 'temp_condition', 'temperature', 'thermostat_status', 'label']


In [11]:
target_cols = list(dataset.columns[-1:])
target_cols

['label']

In [12]:
feature_cols = list(dataset.columns[:-1])
feature_cols

['FC1_Read_Input_Register',
 'FC2_Read_Discrete_Value',
 'FC3_Read_Holding_Register',
 'FC4_Read_Coil',
 'current_temperature',
 'door_state',
 'fridge_temperature',
 'humidity',
 'latitude',
 'light_status',
 'longitude',
 'motion_status',
 'pressure',
 'sphone_signal',
 'temp_condition',
 'temperature',
 'thermostat_status']

**Split Dataset**

In [13]:
# split dataset in features and target variable
X = dataset.drop('label', axis=1) # features
y = dataset['label'] # target variable

In [14]:
X.head()

FC1_Read_Input_Register  FC2_Read_Discrete_Value  \
0                 0.495216                 0.499092   
1                 0.495216                 0.499092   
2                 0.495216                 0.499092   
3                 0.495216                 0.499092   
4                 0.495216                 0.499092   

   FC3_Read_Holding_Register  FC4_Read_Coil  current_temperature  door_state  \
0                   0.488897       0.499405             0.344399           0   
1                   0.488897       0.499405             0.344399           0   
2                   0.488897       0.499405             0.344399           0   
3                   0.488897       0.499405             0.344399           0   
4                   0.488897       0.499405             0.344399           0   

   fridge_temperature  humidity  latitude  light_status  longitude  \
0            0.930769  0.462511  0.008217             0   0.008112   
1            0.588462  0.462511  0.008217             0   0.008112   
2            0.076923  0.462511  0.008217             0   0.008112   
3            0.292308  0.462511  0.008217             0   0.008112   
4            0.746154  0.462511  0.008217             0   0.008112   

   motion_status  pressure  sphone_signal  temp_condition  temperature  \
0              0  0.533556       0.666667             0.2     0.517307   
1              0  0.533556       0.666667             0.2     0.517307   
2              0  0.533556       0.666667             0.8     0.517307   
3              0  0.533556       0.666667             0.8     0.517307   
4              0  0.533556       0.666667             0.2     0.517307   

   thermostat_status  
0                  1  
1                  1  
2                  1  
3                  1  
4                  1

In [15]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

**Splitting Data**

In [16]:
# split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1) # 70% training and 30% test

In [17]:
# check the shape of all of these
print("X_train shape is : ", X_train.shape)
print("X_test shape is : ", X_test.shape)
print("y_train shape is : ", y_train.shape)
print("y_test shape is : ", y_test.shape)

X_train shape is :  (280783, 17)
X_test shape is :  (120336, 17)
y_train shape is :  (280783,)
y_test shape is :  (120336,)


**Building Model**

In [18]:
# calculate start time
start = timeit.default_timer()

# create a Gaussian Classifier
clf = RandomForestClassifier(n_estimators=100)

# train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train, y_train)

# calculate stop time
stop = timeit.default_timer()
train_time = stop - start

In [19]:
# calculate start time
start = timeit.default_timer()

# predict the model
y_pred = clf.predict(X_test)

# calculate stop time
stop = timeit.default_timer()
test_time = stop - start

**Evaluating Model**

In [20]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[69915  3580]
 [12074 34767]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90     73495
           1       0.91      0.74      0.82     46841

    accuracy                           0.87    120336
   macro avg       0.88      0.85      0.86    120336
weighted avg       0.87      0.87      0.87    120336



In [21]:
# model accuracy: how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

# model precision: what percentage of positive tuples are labeled as such?
print("Precision:", metrics.precision_score(y_test, y_pred))

# model recall: what percentage of positive tuples are labelled as such?
print("Recall:", metrics.recall_score(y_test, y_pred))

# calculate F1 Score
print("F1 Score:", metrics.f1_score(y_test, y_pred))

# calculate mean absolute error
print("Mean Absolute Error:", metrics.mean_absolute_error(y_test, y_pred))

# kappa
print("Cohens kappa:", metrics.cohen_kappa_score(y_test, y_pred))

# ROC AUC
print("ROC AUC:", metrics.roc_auc_score(y_test, y_pred))

# train time
print("Train Time(s):", train_time)

# test time
print("Test Time(s):", test_time)

Accuracy: 0.8699142401276426
Precision: 0.9066419798158917
Recall: 0.7422343673277684
F1 Score: 0.8162417241865051
Mean Absolute Error: 0.1300857598723574
Cohens kappa: 0.717103502530847
ROC AUC: 0.8467617853374675
Train Time(s): 96.42210031100012
Test Time(s): 3.5861735989997214


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    precision_score, recall_score, f1_score, ConfusionMatrixDisplay
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN": KNeighborsClassifier(),
    "SVM": SVC(),
}

results = {}

for name, model in models.items():
    print(f"\n--- Training: {name} ---")

    start = timeit.default_timer()
    model.fit(X_train, y_train)
    train_time = timeit.default_timer() - start

    start = timeit.default_timer()
    y_pred = model.predict(X_test)
    test_time = timeit.default_timer() - start

    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    cm = confusion_matrix(y_test, y_pred)

    print(f"Accuracy:  {acc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1 Score:  {f1:.4f}")
    print(f"Train Time: {train_time:.2f} sec")
    print(f"Test Time:  {test_time:.2f} sec")
    print("Confusion Matrix:\n", cm)

    results[name] = {
        "model": model,
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1_score": f1,
        "train_time": train_time,
        "test_time": test_time,
        "confusion_matrix": cm,
        "predictions": y_pred
    }


--- Training: Decision Tree ---
Accuracy:  0.8648
Precision: 0.8936
Recall:    0.7408
F1 Score:  0.8100
Train Time: 2.86 sec
Test Time:  0.04 sec
Confusion Matrix:
 [[69363  4132]
 [12143 34698]]

--- Training: Random Forest ---
Accuracy:  0.8699
Precision: 0.9066
Recall:    0.7423
F1 Score:  0.8162
Train Time: 91.82 sec
Test Time:  3.85 sec
Confusion Matrix:
 [[69913  3582]
 [12073 34768]]

--- Training: Logistic Regression ---
Accuracy:  0.6889
Precision: 0.8748
Recall:    0.2342
F1 Score:  0.3695
Train Time: 2.65 sec
Test Time:  0.01 sec
Confusion Matrix:
 [[71925  1570]
 [35869 10972]]

--- Training: SVM ---


In [ ]:
plt.figure(figsize=(8, 5))
plt.bar(results.keys(), [results[m]['accuracy'] * 100 for m in results], color='mediumseagreen')
plt.title("Model Accuracy Comparison - TON IoT Dataset")
plt.ylabel("Accuracy (%)")
plt.xlabel("Model")
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.tight_layout()
plt.show()


In [ ]:
from sklearn.metrics import ConfusionMatrixDisplay

for name, model_data in results.items():
    cm = model_data["confusion_matrix"]
    labels = [0, 1]
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
    disp.plot(cmap=plt.cm.Blues)
    plt.title(f"Confusion Matrix - {name}")
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.show()